version: '3'

services:
  rails:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - unixsck:/var/run/
    depends_on:
      - db
  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust 
    volumes:
      - unixsck:/var/run/
      - db:/var/lib/postgresql/data/

volumes:
  unixsck:
  db:

